version: '{build}'

environment:
    PATH: 'C:\Ruby200\bin;%PATH%'

install:
    - cmd: bundle install

build_script:
    - cmd: build.netstd.cmd

nuget:
    disable_publish_on_pr: true

test: off

on_finish:
    - ps: $root = Resolve-Path .\artifacts; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName to-publish }
