version: '{build}'

pull_requests:
  do_not_increment_build_number: true

environment:
    PATH: 'C:\Ruby200\bin;%PATH%'
    BUILD: $(APPVEYOR_BUILD_NUMBER)

install:
    - cmd: bundle install

build_script:
    - cmd: build.cmd

nuget:
    disable_publish_on_pr: true

test: off

artifacts:
    - path: .\artifacts\*\*
