version: '{build}'

environment:
    PATH: 'C:\Ruby200\bin;%PATH%'

install:
    - cmd: bundle install

build_script:
    - cmd: build.cmd
    - cmd: build.netstd.cmd

nuget:
    disable_publish_on_pr: true

test: off

artifacts:
    - path: .\artifacts\logs\*.*
    - path: .\artifacts\output\*-netstd.nupkg
    - path: .\artifacts\output
    - path: .\artifacts\tests\*.*
